import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'

import { NavigationBar } from './components/NavigationBar'

import './globals.css'

const bernoru = localFont({
  src: '../public/fonts/bernoru-blackultraexpanded.otf',
  variable: '--font-bernoru',
})

const cochin = localFont({
  src: '../public/fonts/cochin-regular.otf',
  variable: '--font-conchin',
})

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${bernoru.variable} ${cochin.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col pt-16 ">
        <NavigationBar />
        {children}
      </body>
    </html>
  )
}
